### ISSUE TITLE
Cannot compile shared library on msys2 mingw-w64

### ISSUE THREAD

**Issue by ashutoshmahajan** [coin-or/CoinUtils#120]
Trying to configure and make releases/2.11.4 for shared libraries on MSYS2 (mingw-w64). It fails with the message. configure runs fine and shows that it will try to build shared libs, make also works but does not produce shared libraries, it switches over to static files with the following messages.

./configure --enable-shared --disable-static --enable-dependency-linking
make install

*** Warning: linker path does not have real file for library -lblas.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libblas and none of the candidates passed a file format test
*** using a file magic. Last file checked: /mingw64/bin/libblas.dll

...

*** Since this library must not contain undefined symbols,
*** because either the platform does not support them or
*** it was explicitly requested with -no-undefined,
*** libtool will only create a static version of it.

The master branch seems to compile well and generate the dll files. We want to distribute a release version of Cbc and Ipopt for a Scilab toolbox we are working on. It requires dll files. Requesting a push of changes to a new release! Thanks for the great work.

**Comment by tkralphs** [comment]
We have only just recently (within the past month or two) finally completed a years-long effort to re-write our build system in order to accommodate the building of DLLs with the autotools. As such, it is currently only supported in the maser branch. There is a bit more work to do before we can push master out to a new stable and then a release. I'll push this along as quickly as I can, but not guarantees. In the meantime, there might be ways to get a DLL from current stables witha bit more work. What were you doing previously?

**Comment by ashutoshmahajan** [comment]
Thanks Ted. If you have any suggestions for changing current stables, we can try. We were earlier using some very old binaries of IPOPT and Cbc available online.

**Comment by tkralphs** [comment]
Depending on how much it's worth to you, you could relatively easily put the new build harness on top of the current release(s). I only say "easily" because I think it should be easy for you, since you know something about the autotools and our build system. We're not going to do this publicly ourselves to avoid breaking existing processes that depend on the old build system, but for your own personal use, it should not be a problem. Let me know if you want to do it and if it's not clear how.

**Comment by svigerske** [comment]
I'm not so sure that this would be "easy". There were also changes in the source itself (for CoinUtils, f6fb297c6d2f947f5de3a3169b6bfcbc53a642b1 touched 117 files) that may not be so easy to apply to current stables, also since he actually wants more than only CoinUtils.

**Comment by tkralphs** [comment]
OK, maybe you are right. I didn't realize that there was a bunch of `_declspec` stuff involved. It's probably not worth it. I'll do my best to get moving on the steps needed for making new stables and releases.

**Comment by tkralphs** [comment]
I'll close this for now.
