### ISSUE TITLE
Build of stable/2.11 sometimes fails

### ISSUE THREAD

**Issue by tkralphs** [coin-or/CoinUtils#130]
I haven't tried to replicate this yet, just putting here in case someone can spot the issue more easily than me. A build of DIP failed with MVSVC++ compiler (no Fortran compiler), but building some third party projects. `F77_FUNC` ended up not being defined, although `COIN_FACTORIZATION_DENSE_CODE` is `1`. I guess some logic is missing somewhere. It's not really an issue for me, I'm just going to add `--no-third-party`, but I guess we could try to track it down.

**Comment by svigerske** [comment]
Can happen if it picked up MKL for Lapack using a linking check in C instead of Fortran.
I copied the hack from https://github.com/coin-or/Ipopt/blob/stable/3.12/Ipopt/src/Common/IpoptConfig.h#L46 to here.

Should be better on master, as that doesn't assume anymore that you need to have Fortran to use a library that may (but actually may not) be written in Fortran.

**Comment by tkralphs** [comment]
Thanks, I had meant to give a link to the failure, so here it is for posterity: https://ci.appveyor.com/project/tkralphs/dip-qk8he/builds/32275615/job/e5gvcq76rhgeabl8
