### ISSUE TITLE
constraint lines of length 903 lead to readthrough into following line

### ISSUE THREAD

**Issue by dlaehnemann** [coin-or/CoinUtils#146]
This is a follow-up to issue #144, that lead to a fix for that parsing problem (see [this commit](https://github.com/coin-or/CoinUtils/commit/63eaa7af9a5329fdf2fc865117c0da2a28515bc9)). Once that problem was fixed, my larger file started throwing other errors, and this one seems to again be related to buffer sizes. In a larger file, I had three instances of constraint lines of the exact length of `903` characters, and in each of these cases this lead to a read through into the next line and then a complaint about the name of the next constraint not being a valid column name:
```
Welcome to the CBC MILP Solver
Version: devel
Build Date: Feb 18 2021

command line - /path/to/bin/cbc new_buffer_problem.lp solve (default strategy 1)
 CoinLpIO::readLp(): Maximization problem reformulated as minimization
### CoinLpIO::is_invalid_name(): Name c12054: contains illegal character ':'
### CoinLpIO::is_invalid_name(): Name c16238: contains illegal character ':'
### CoinLpIO::is_invalid_name(): Name c17452: contains illegal character ':'
### CoinLpIO::readLp(): Invalid column names
Now using default column names.
```

I isolated the second instance from the larger file for testing purposes (simply replace the `.txt` extension with `.lp`):
[constraint_line_length_903_problem.txt](https://github.com/coin-or/CoinUtils/files/6004964/constraint_line_length_903_problem.txt)

This should give only the second error message:
```
Welcome to the CBC MILP Solver 
Version: devel 
Build Date: Feb 18 2021 

command line - /path/to/bin/cbc constraint_line_length_903_problem.lp solve (default strategy 1)
 CoinLpIO::readLp(): Maximization problem reformulated as minimization
### CoinLpIO::is_invalid_name(): Name c16238: contains illegal character ':'
### CoinLpIO::readLp(): Invalid column names
Now using default column names.
```

**Comment by jjhforrest** [comment]
David,

Thanks - will fix tomorrow.  Will get there in a day or two.

John Forrest

**Comment by dlaehnemann** [comment]
Hi John,

Thanks again!

Also, do you have any pointers to a release schedule for the COIN-OR projects? I can't seem to find any info on that and was wondering how long it would be, until the respective changes are part of a released version of `cbc`.

Best regards,
David

**Comment by tkralphs** [comment]
The releases are usually done by either @svigerske or me. We are volunteers with day jobs, so there's not much of a fixed schedule to it, but if the fix is to an existing stable version and everything looks good in the automated testing, it's not very difficult to push out a release if the fix is critical. These recent fixes could pretty easily be cherry-picked over to stable and a release made. Pushing out a release of Cbc means pushing out releases of all dependent projects, which is a bit more work, but there have been some recent fixes there, too, so it might be needed. However, the current release of Cbc should work fine with any release of CoinUtils in the same stable series and `coinbrew` will automatically pick up the latest of those. 

At the moment, the `master` branch of CoinUtils is undergoing some refactoring (in a separate branch) and I'm hoping to finish that before pushing out a new stable version, at which time everything currently in master will go to release. It could be a bit of time before that happens.

**Comment by dlaehnemann** [comment]
Thanks for the detailed response, this gives a very good picture of how things work over here! I was mainly curious for an idea of the time frame. And I think any of the things I raised can be worked around (or fixed elsewhere, in the case of the missing eol at ends of files in issue #145). So it's not urgent, especially as it sounds like a new release is incoming in the midterm.

And thanks for all the volunteer work on this project. This is very much appreciated and very useful!

**Comment by jjhforrest** [comment]
David,

Updated master - your three (and twenty others) work.

Had fun with input.  The code uses fgets and if the only character it is 
reading is \n it does not store it.  Using getc gets round that and I 
also used ungetc in end!

John Forrest

**Comment by dlaehnemann** [comment]
Closed by @jjhforrest via https://github.com/coin-or/CoinUtils/commit/86ab8d39f90f3119ce372ff88c9e62b54dc2cfe9

**Comment by dlaehnemann** [comment]
Thanks again, @jjhforrest ! The changes do look like some fun with input parsing...

Sorry if this whole thing might start to seem a bit like a game of whack-a-mole, but I have now found this new issue with my input: #147

This time around, I also included the larger input file that I keep on extracting these examples from. It seems to be a rich resource for corner cases in the lp format...
