### ISSUE TITLE
Eliminate Appveyor config, move to Github Actions

### ISSUE THREAD

**Issue by xmunoz** [coin-or/CoinUtils#154]
With [Bintray](https://bintray.com/) shutting down, we now want the canonical place that binaries live to be Github Releases.

**Comment by xmunoz** [comment]
After reading some of the [AppVeyor documentation](https://www.appveyor.com/docs/deployment/github/) on the subject, it's not clear to me if packages can be automatically uploaded to existing releases. I'm tempted to see if we can just move the windows builds to Github actions, and use the same workflow for releasing that we've already implemented.

**Comment by tkralphs** [comment]
It seems like if nothing else, we can just use the Github API to do what we want manually rather than using their system. But then we have to encrypt the token and authenticate using that encrypted variable, which I suspect you won't like :). Alternatively, I didn't really see any reason why our current workflow would not be able to do Windows builds on Actions and eliminating Appveyor would have a lot of benefits.

**Comment by xmunoz** [comment]
I've removed the appveyor webhook. This repository is now only using Github Actions for CI and releasing.

**Comment by xmunoz** [comment]
Once we comfortable with this new CI, we might also consider deleting the project from Appveyor: https://ci.appveyor.com/project/coin-or/coinutils/settings/delete

**Comment by tkralphs** [comment]
Before we're completely free of Appveyor, we need to test all of this in the current stable branches. I expect and hope that it will all work the same way there. I guess I would not delete the project from Appveyor, though, since I often look back at old builds when something breaks that used to work. The build history is nice to have. As long as we don't point to it anymore, do you think it's bad to have it around?

**Comment by xmunoz** [comment]
I created a separate issue for that. I'll let you handle it since I don't really understand the branching and releasing strategy of this project.

**Comment by tkralphs** [comment]
OK, yup, I can do that. If you're interested in the workflows, they are documented here: https://coin-or.github.io/developer_introduction.html#standard-development-workflows. If you look at this document, you may be the first to do so :). The workflows are a little different than the usual git workflows, but these projects started being managed in CVS, then moved to SVN, and now have moved to git quite recently. Using a workflow somewhat close to what the main developers have gotten used to over more than a decade seemed the best way forward we first moved to git (In fact, we were at first mirroring from SVN to git. The workflows could change in the future, but that would come with a rather large disruption cost. Given the level of development, we've opted for status quo.
